### ISSUE TITLE
Could Touche be adapted for Boffer Combat?

### ISSUE THREAD

**Issue by DrAlta** [Yohannfra/Touche#11]
Hello. I was to use an automated scoring system for my Boffer Combat.

The main things I can think of is that Boffer Combat has many opponents at one and multi hit locations.

Would I just have change the software to track more that 2 combatants then to change the hardware to add multiple lamè connectors?

Edit: correct epee to lamè

**Comment by Yohannfra** [comment]
Hello. 
I don't know anything about Boffer Combat, is there already an electric system (wireless or no) that works ?

A fencing epee/foil has a button and an electric wire within the blade conducting the button state, I don't think there is something similar for Boffer Combat weapons.

**Comment by DrAlta** [comment]
I just learned the the Epee is a type of weapon the armor is called lamè.

I failed the math part of first semester of Electronic Repair Technician program I was in, now I do software.
I don't know of any automatic scoring systems than Fencing's and Unified Weapons Master which w never released and has been quite since 2017.

How do you detect if a hit is valid?

I guess it would be more like sabre which you don't support yet....

**Comment by Yohannfra** [comment]
I detect if a hit occurred using the button at the tip of the epee/foil.

Yes it's more like sabre and seems to be more complicated since weapons are in foam.

I think this is out the scope of Touché for now and prefer to stay focused on traditional fencing with foil, epee and sabre.

You can still fork and try to find a way to make it work but I don't think it will be trivial.
